-- 코드를 입력하세요
SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM(SALES * PRICE) AS TOTAL_SALES
FROM BOOK AS B 
JOIN BOOK_SALES AS S ON S.BOOK_ID = B.BOOK_ID
JOIN AUTHOR  AS A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE  YEAR(SALES_DATE) = 2022 AND MONTH(SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID ASC, B.CATEGORY DESC