SELECT I.REST_ID,	REST_NAME,	FOOD_TYPE,	FAVORITES,	ADDRESS,ROUND(AVG(REVIEW_SCORE),2) AS SCORE
FROM REST_REVIEW AS R
JOIN REST_INFO AS I ON R.REST_ID = I.REST_ID
WHERE I.ADDRESS LIKE "서울%"
GROUP BY I.REST_ID
ORDER BY SCORE DESC, FAVORITES DESC