-- 코드를 입력하세요
SELECT REVIEW.REST_ID, REST_NAME,	FOOD_TYPE,	FAVORITES,	ADDRESS, ROUND(AVG(REVIEW_SCORE),2) SCORE
FROM REST_REVIEW REVIEW
LEFT JOIN REST_INFO INFO ON REVIEW.REST_ID = INFO.REST_ID
WHERE ADDRESS LIKE '서울%'
GROUP BY REST_ID
ORDER BY SCORE DESC, FAVORITES DESC